
apiVersion: v1
kind: Secret
metadata:
  name: keda-rabbitmq-secret
data:
  host: "c3dhdGhp"
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-rabbitmq-conn
spec:
  secretTargetRef:
    - parameter: host
      name: keda-rabbitmq-secret
      key: host
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: { .Chart.Name }-keda
spec:
  scaleTargetRef:
    kind: Deployment
    name: { template "fiposprocessorservice.deployName" . }
  minReplicaCount: { .Values.replicaCount.min }
  maxReplicaCount: { .Values.replicaCount.max }
  triggers:
  - type: rabbitmq
    metadata:
      protocol: "amqp"
      queueName: "fiposprocessor_request_mq"
      queueLength: "1"
    authenticationRef:
      name: keda-trigger-auth-rabbitmq-conn

    